# Используйте официальный образ .NET 6.0 как базовый образ
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Используйте официальный образ .NET SDK 6.0 для сборки приложения
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TelegramBotWebhook/TelegramBotWebhook.csproj", "TelegramBotWebhook/"]
RUN dotnet restore "TelegramBotWebhook/TelegramBotWebhook.csproj"
COPY . .
WORKDIR "/src/TelegramBotWebhook"
RUN dotnet build "TelegramBotWebhook.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TelegramBotWebhook.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TelegramBotWebhook.dll"]
